
pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    strategy:
      matrix:
        check:
          os: linux
          python: '3.6'
        lint:
          os: linux
          python: '3.6'
        docs_build:
          os: linux
          python: '3.6'
        docs_linkcheck:
          os: linux
          python: '3.6'
        condarecipe:
          os: linux
          python: '3.6'
        py27-notebook:
          os: linux
          python: '2.7'
        py36-notebook54:
          os: linux
          python: '3.6'
        py36-notebook55:
          os: linux
          python: '3.6'
        py36-notebook44:
          os: linux
          python: '3.6'
        py36-notebook:
          os: linux
          python: '3.6'
        py36-appveyorartifacts:
          os: linux
          python: '3.6'

# resources:
#   containers:
#     - container: global
#       env: { LD_PRELOAD: /lib/x86_64-linux-gnu/libSegFault.so
#              SEGFAULT_SIGNALS: all}

- script: |
    uname -a
    id -un
    id -Gn
    # stuff for conda recipe
    'if [[ ${TOXENV} == "condarecipe" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi'
    'if [[ ${TOXENV} == "condarecipe" ]]; then bash miniconda.sh -b -p $HOME/miniconda; fi'
    'if [[ ${TOXENV} == "condarecipe" ]]; then export PATH="$HOME/miniconda/bin:$PATH"; fi'
    'if [[ ${TOXENV} == "condarecipe" ]]; then hash -r; fi'
    'if [[ ${TOXENV} == "condarecipe" ]]; then conda config --set always_yes yes --set changeps1 no; fi'
    'if [[ ${TOXENV} == "condarecipe" ]]; then conda info -a; fi  # Useful for debugging any issues with conda'
    'if [[ ${TOXENV} == "condarecipe" ]]; then conda install conda-build; fi'
    'if [[ ${TOXENV} == "condarecipe" ]]; then conda config --append channels conda-forge; fi  # add conda-forge channel at lower priority than defaults'
    'if [[ ${TOXENV} == "condarecipe" ]]; then git fetch --unshallow; fi'
  displayName: 'Before Install'
  continueOnError: false

- script: |
    pip install tox
    virtualenv --version
  displauName: 'Install'
  continueOnError: false

steps:
  - script: tox -v -e ${Build}
  - 'if ! [[ ${TOXENV} =~ ^(appveyorartifacts|check|condarecipe|docs|lint)$ ]]; then tox -e coveralls,codecov; fi'
  displayName: Script







