
pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    check:
      name: check
      python: '3.6'
    lint:
      name: lint
      python: '3.6'
    # docs_build:
    #   # os: linux
    #   python: '3.6'
    # docs_linkcheck:
    #   # os: linux
    #   python: '3.6'
    # condarecipe:
    #   # os: linux
    #   python: '3.6'
    # py27-notebook:
    #   # os: linux
    #   python: '2.7'
    # py36-notebook54:
    #   # os: linux
    #   python: '3.6'
    # py36-notebook55:
    #   # os: linux
    #   python: '3.6'
    # py36-notebook44:
    #   # os: linux
    #   python: '3.6'
    # py36-notebook:
    #   # os: linux
    #   python: '3.6'
    # py36-appveyorartifacts:
    #   # os: linux
    #   python: '3.6'

steps:
- script: |
    uname -a
    id -un
    id -Gn
    # stuff for conda recipe
    if [[ $(python) == "3.6" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
    if [[ $(python) == "3.6" ]]; then bash Miniconda3-latest-Linux-x86_64 -b -p $HOME/miniconda; fi
    if [[ $(python) == "3.6" ]]; then export PATH="$HOME/miniconda/bin:$PATH"; fi
    if [[ $(python) == "3.6" ]]; then hash -r; fi
    if [[ $(python) == "3.6" ]]; then conda config --set always_yes yes --set changeps1 no; fi
    if [[ $(python) == "3.6" ]]; then conda info -a; fi  # Useful for debugging any issues with conda
    if [[ $(python) == "3.6" ]]; then conda install conda-build; fi
    if [[ $(python) == "3.6" ]]; then conda config --append channels conda-forge; fi  # add conda-forge channel at lower priority than defaults
    if [[ $(python) == "3.6" ]]; then git fetch; fi
  displayName: 'Before Install'
  continueOnError: false

- script: |
    pip install virtualenv
    sudo /usr/bin/easy_install virtualenv
    pip install wheel
    python setup.py bdist_wheel 
    pip install tox
    virtualenv --version
  displayName: 'Install'
  continueOnError: false

- script: |
    ~/.local/bin/tox -v -e $(name)
    if ! [[ $(python) == "3.6" ]]; then ~/.local/bin/tox -e coveralls,codecov; fi
  displayName: 'Script'
  continueOnError: false







