
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt update
    sudo apt install python3.6
    sudo apt-get install pandoc
    sudo apt-get install inkscape
    pip3 install wheel
    python3 setup.py bdist_wheel
    sudo apt-get install python3-setuptools
    pip3 install tox
    ~/.local/bin/tox
  displayName: 'Run Tests'
  continueOnError: false  




