
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt update
    sudo apt install python3.6
    sudo apt-get install pandoc
    sudo apt-get install inkscape
    pip3 install wheel
    python3 setup.py bdist_wheel
    sudo apt-get install python3-setuptools
    pip3 install tox
  displayName: 'Setup Tests'
  continueOnError: false

- script: |
    ~/.local/bin/tox -v -e check
    ~/.local/bin/tox -v -e lint
    ~/.local/bin/tox -v -e docs_build
    ~/.local/bin/tox -v -e docs_linkcheck
    ~/.local/bin/tox -v -e py27-notebook
    ~/.local/bin/tox -v -e py36-notebook54
    ~/.local/bin/tox -v -e py36-notebook55
    ~/.local/bin/tox -v -e py36-notebook44
    ~/.local/bin/tox -v -e py36-notebook
    ~/.local/bin/tox -v -e appveyorartifacts
  displayName: 'Run Tests'
  continueOnError: false 

- script: |
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda info -a
    conda install conda-build
    conda config --append channels conda-forge
    git fetch --unshallow
    ~/.local/bin/tox -v -e condarecipe
  displayName: 'Run condarecipe'
  continueOnError: false


